export const contactList = [
    {
        id: 1,
        name: "Ayush Kulshrestha",
        profilePic: "/whatsapp-clone/profile/ayushk.jpeg",
        lastText: "Hey Man",
        lastTextTime: "12:58 PM",
    },
    {
        id: 2,
        name: "John Appleseed",
        profilePic: "/whatsapp-clone/profile/theindiandev.jpeg",
        lastText: `I'm with @theindiandev`,
        lastTextTime: "12:45 PM",
    },
    {
        id: 3,
        name: "Elon Bezoz",
        profilePic: "/whatsapp-clone/profile/elon.jpeg",
        lastText: "Where is my Tesla?",
        lastTextTime: "12:30 PM",
    },
    {
        id: 4,
        name: "Jeff Musk",
        profilePic: "/whatsapp-clone/profile/jeff.jpeg",
        lastText: "Travelling to space",
        lastTextTime: "12:00 PM",
    },
];
export const messagesList = [
    {
        id: 1,
        messageType: "TEXT",
        text: "Hey Man 😁",
        sender: 0,
        addedOn: "12:00 PM",
    },
    {
        id: 2,
        messageType: "TEXT",
        text: "Hey, What's up?",
        sender: 1,
        addedOn: "12:01 PM",
    },
    {
        id: 3,
        messageType: "TEXT",
        text: "All Good, What about you?",
        sender: 0,
        addedOn: "12:00 PM",
    },
    {
        id: 4,
        messageType: "TEXT",
        text: "I'm good as well",
        sender: 1,
        addedOn: "12:00 PM",
    },
    {
        id: 5,
        messageType: "TEXT",
        text: "Great 😁",
        sender: 0,
        addedOn: "12:00 PM",
    },
    {
        id: 5,
        messageType: "TEXT",
        text: "Have you subscribed The Indian Dev ?",
        sender: 1,
        addedOn: "12:00 PM",
    },
    {
        conversation_id: "6350c1218d1cabf145ec9063",
        sender: "631f06a6d7d3d1a58d957e95",
        text: "Halooooooooooooooo",
    },
    {
        conversation_id: "6350c1218d1cabf145ec9063",
        sender: "634bad9b5ae448375782944b",
        text: "12345566",
        __v: 0,
        _id: "63514378ba6a63031e990f2e",
    },
];
